name: agora_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter
